# Generated by Django 2.0.6 on 2018-07-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('emp_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='gpxcontentTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=500)),
                ('longitude', models.CharField(max_length=500)),
                ('latitude', models.CharField(max_length=500)),
                ('altitude', models.CharField(max_length=500)),
                ('time', models.TimeField()),
                ('Speed', models.IntegerField()),
                ('point', models.CharField(default=None, max_length=1000)),
            ],
        ),
    ]
