# Generated by Django 2.0.6 on 2018-08-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_gpxjson'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataSet2Analysis',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=500)),
                ('altitude', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=500)),
                ('Speed', models.CharField(max_length=500)),
                ('TimeDiff', models.CharField(max_length=500)),
                ('DeltaElev', models.CharField(max_length=500)),
                ('TotalDist', models.CharField(max_length=500)),
                ('Angle', models.CharField(max_length=500)),
            ],
        ),
    ]
