# Generated by Django 2.0.6 on 2018-08-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_dataset2analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxjson',
            name='GroupNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
